### ISSUE TITLE
Update labs-ember-search

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ember-search#50]
# This issue is closed when Ember is version 3.19 and the app builds in Netlify for Node 14/16

**Comment by allthesignals** [comment]
This is PR'd but in draft: https://github.com/NYCPlanning/labs-ember-search/pull/44 @allthesignals to double-check why and make sure it's ready for review

**Comment by allthesignals** [comment]
This PR is awaiting review @TylerMatteo

**Comment by allthesignals** [comment]
Moving this to Ready for Acceptance

**Comment by TylerMatteo** [comment]
@allthesignals  just housekeeping - I'd consider this done with the release of `@nycplanning/ember` and successful integration of it into Zola.
